### ISSUE TITLE
Reference Paper

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [gridap/GridapEmbedded.jl#17]
what is the reference journal article/ theory manual for "GridapEmbedded.jl"?

**Comment by fverdugo** [comment]
At the moment, we don't have documentation specific for the project GridapEmbedded.

Alternatively, You can take a look to our latest papers on our research on embedded FE methods:

1.
https://doi.org/10.1016/j.cma.2018.03.022
https://arxiv.org/abs/1709.09122

2.
https://doi.org/10.1016/j.cma.2019.112583
https://arxiv.org/abs/1902.01168

3.
https://arxiv.org/abs/2006.05373
