### ISSUE TITLE
Aggreagation in Space-Time Problems

### ISSUE THREAD

**Issue by diliphridya** [gridap/GridapEmbedded.jl#21]
@fverdugo @santiagobadia 
When dealing with space-time AgFEM, how can we aggregate only in space and not time ?

**Comment by santiagobadia** [comment]
Based on the comments so far, I would define first a mask that tells you which faces are suitable for aggregation at each cell. Then, I would generate a global array with this info, using, e.g., `Fill(mask,num_cells)`, and finally, I would create a new array that combines the standard `cell_faces` and this one to provide you a new `cell_faces_after_filter`. Next, you can use everything you need. I can provide details about ho to do this.
