### ISSUE TITLE
Commutativity not holding on interface bilinear form

### ISSUE THREAD

**Issue by ericneiva** [gridap/GridapEmbedded.jl#24]
Dear @fverdugo,

I am using GridapEmbedded v0.3.1 and Gridap v0.13.4 and I face the following issue:

At [this line](https://github.com/gridap/GridapEmbedded.jl/blob/master/test/GridapEmbeddedTests/BimaterialPoissonCutFEMTests.jl#L148) of the Bimaterial Poisson CutFEM Test, if I commute the second term, i.e. I have `mean_q(u)*jump_u(v)`, the test no longer passes.

Do you have any insight why this happens?

Thanks for taking a look at it. Regards.

**Comment by fverdugo** [comment]
Perhaps this is related with https://github.com/gridap/Gridap.jl/issues/349, which is solved in Gridap@0.14.0

I recommend to update to Gridap@0.14.0 and see if the error persists.

**Comment by fverdugo** [comment]
BTW, to upgrade to Gridap@0.14.0 you will need to do some replacements analogous to this one `Table{Int,Int32}` -> `Table{Int,Vector{Int},Vector{Int32}}`  in GridapEmbedded

**Comment by ericneiva** [comment]
Great, @fverdugo, I'll accommodate the changes of Gridap@0.14.0 into GridapEmbedded and see if that fixes the issue.

I want to confirm the procedure, though. I saw there is an open PR #23... Shall I work on the branch of this PR?

**Comment by fverdugo** [comment]
>  I saw there is an open PR #23... Shall I work on the branch of this PR?

Yes! sounds like a good idea. Thanks!
