### ISSUE TITLE
Poisson Equation solver yields high errors when the geometry is aligned to the boundary

### ISSUE THREAD

**Issue by diliphridya** [gridap/GridapEmbedded.jl#34]
@fverdugo @santiagobadia 
If we consider a geometry that is not aligned with the boundary of the background mesh, then the L2-error is within the tolerance in the following code.

```
using Gridap
using GridapEmbedded
using Gridap.ReferenceFEs

u(x) = x[1] - x[2]
f(x) = -Δ(u)(x)
ud(x) = u(x)

L = 1.0
domain = (0.0,L,0.0,L)
n = 5
partition = (n,n)
bgmodel = CartesianDiscreteModel(domain,partition)
h = L/n

geo = quadrilateral(x0=Point(0.1,0.1),d1=VectorValue(0.8,0.0),d2=VectorValue(0.0,0.8))
cutgeo = cut(bgmodel,geo)

strategy = AggregateAllCutCells()
aggregates = aggregate(strategy,cutgeo)

trian_Ω = Triangulation(cutgeo)
trian_Γ = EmbeddedBoundary(cutgeo)

n_Γ = get_normal_vector(trian_Γ)

order = 1
quad_Ω = CellQuadrature(trian_Ω,2*order)
quad_Γ = CellQuadrature(trian_Γ,2*order)

model = DiscreteModel(cutgeo)
trian = Triangulation(bgmodel)
writevtk(trian,"bgtrian")
writevtk(trian_Ω,"trian_o")
writevtk(trian_Γ,"trian_g",cellfields=["n_g"=>n_Γ])

T = Float64
reffe = LagrangianRefFE(T,QUAD,order)
conf = CDConformity((CONT,CONT))
Vstd = TestFESpace(model=model,reffe=reffe,conformity=conf,dof_space=:physical)
V = AgFEMSpace(Vstd,aggregates)
U = TrialFESpace(V)

γd = 10.0
a_Ω(u,v) = ∇(v)⊙∇(u)
l_Ω(v) = v*f
a_Γ(u,v) = (γd/h)*v*u  - v*(n_Γ⋅∇(u)) - (n_Γ⋅∇(v))*u
l_Γ(v) = (γd/h)*v*ud - (n_Γ⋅∇(v))*ud

t_Ω = AffineFETerm(a_Ω,l_Ω,trian_Ω,quad_Ω)
t_Γ = AffineFETerm(a_Γ,l_Γ,trian_Γ,quad_Γ)
op = AffineFEOperator(U,V,t_Ω,t_Γ)
uh = solve(op)

uh_Ω = restrict(uh,trian_Ω)

e = u - uh_Ω
el2 = sqrt(sum(integrate(e*e,trian_Ω,quad_Ω)))

tol = 1.0e-10
@assert el2<tol

writevtk(trian_Ω,"sol",cellfields=["uh"=>uh_Ω])

```

![Screenshot from 2020-11-13 18-23-48](https://user-images.githubusercontent.com/53897026/99040924-1af28180-25de-11eb-813d-05614bcec74a.png)

Now if we change the geometry to :
```
geo = quadrilateral(x0=Point(0.1,0.0),d1=VectorValue(0.8,0.0),d2=VectorValue(0.0,1.0))
```
Then the L2-error is above the tolerance. When the geometry is aligned with the top and bottom boundary of the background mesh the error is high.

![Screenshot from 2020-11-13 18-25-37](https://user-images.githubusercontent.com/53897026/99040990-36f62300-25de-11eb-88f7-50a03665d19e.png)

**Comment by fverdugo** [comment]
Hi @diliphridya 

I suggest to generate a levelset larger than your background mesh. Then, you can extract the embedded boundary (as now) but also the interior part of the boundary of the background mesh. See this picture:
![drawing2](https://user-images.githubusercontent.com/48508177/99046510-240a3100-2593-11eb-8547-78d399fbafe7.png)

Find here 
https://github.com/gridap/GridapEmbedded.jl/blob/master/test/InterfacesTests/EmbeddedFacetDiscretizationsTests.jl
an example on how generate the `cutgeo_facets` object

**Comment by diliphridya** [comment]
Thanks @fverdugo .
